@echo off
REM Set path names (system dependant)

SET CONTROL=SerialTools
SET DLLNAME=SerialCE.dll

SET INPUTPATH=e:\NSBCE7\Controls\%CONTROL%\Binaries\
SET OUPUTPATH=e:\NSBCE7\600

copy %INPUTPATH%\HPC2000\ARM\%DLLNAME%    %OUPUTPATH%\HPC2000\ARM
copy %INPUTPATH%\HPC2000\MIPS\%DLLNAME%   %OUPUTPATH%\HPC2000\MIPS

copy %INPUTPATH%\HPC_1824\%DLLNAME%       %OUPUTPATH%\HPC_1824
copy %INPUTPATH%\HPC_2577\%DLLNAME%       %OUPUTPATH%\HPC_2577
copy %INPUTPATH%\CE420_MIPSII\%DLLNAME%   %OUPUTPATH%\HPC_4000

copy %INPUTPATH%\HPCPRO\ARM\%DLLNAME%     %OUPUTPATH%\HPCPRO\ARM
copy %INPUTPATH%\HPCPRO\MIPS\%DLLNAME%    %OUPUTPATH%\HPCPRO\MIPS
copy %INPUTPATH%\HPCPRO\SH3\%DLLNAME%     %OUPUTPATH%\HPCPRO\SH3
copy %INPUTPATH%\HPCPRO\SH4\%DLLNAME%     %OUPUTPATH%\HPCPRO\SH4

copy %INPUTPATH%\PocketPC\ARM\%DLLNAME%   %OUPUTPATH%\PocketPC\ARM
copy %INPUTPATH%\PocketPC\MIPS\%DLLNAME%  %OUPUTPATH%\PocketPC\MIPS
copy %INPUTPATH%\PocketPC\SH3\%DLLNAME%   %OUPUTPATH%\PocketPC\SH3

copy %INPUTPATH%\PocketPC2003\%DLLNAME%   %OUPUTPATH%\PocketPC2003

copy %INPUTPATH%\PPC\MIPS\%DLLNAME%       %OUPUTPATH%\PPC\MIPS
copy %INPUTPATH%\PPC\SH3\%DLLNAME%        %OUPUTPATH%\PPC\SH3

copy %INPUTPATH%\Desktop\SerialXP.dll     e:\NSBCE7\Files\dll
