#ifndef _TPOOLLIBRARY_OLEDATECONVERSIONS_H_
#define _TPOOLLIBRARY_OLEDATECONVERSIONS_H_

BOOL    hlpOleDateFromSystemType(SYSTEMTIME* pst, DATE& dtDest);
BOOL	hlpOleDateToSystemType(DATE dtSrc, SYSTEMTIME& tmDest);
BOOL	hlpOleDateFromSystemTime(SYSTEMTIME* pstIn, DATE& dtDest);

#ifndef OLEDATECONV_HELPERS_PARSERS
	BOOL ODC_ParseDateTime(LPCSTR szTime,SYSTEMTIME& stDest);
#endif // OLEDATECONV_HELPERS_PARSERS

#endif // _TPOOLLIBRARY_OLEDATECONVERSIONS_H_