<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: EVC3 - Win32 (WCE ARM) PPC2002_Release--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\GEORGE~1\LOCALS~1\Temp\RSP8.tmp" with contents
[
/nologo /W3 /I "../include" /D "_USRDLL" /D "WIN32_PLATFORM_HPC2000" /D "ARM" /D "_ARM_" /D UNDER_CE=300 /D _WIN32_WCE=300 /D "UNICODE" /D "_UNICODE" /D "NDEBUG" /Fo"output/" /Oxs /MC /c 
"E:\NSBCE6\Controls\NSBComDlg\src\ComDlgMiniEnum.cpp"
]
Creating command line "clarm.exe @C:\DOCUME~1\GEORGE~1\LOCALS~1\Temp\RSP8.tmp" 
<h3>Output Window</h3>
Compiling...
ComDlgMiniEnum.cpp
Including osspecific helpers byte order,string lengths, etc. (osspecific.h) - link with: osspecific.cpp
Defining default machine byte order little endian - COMMON_SYSTEM_BYTEORDER[_XXXX] (osspecific.h)
Mapping the stand alone os specific routines to the default names (may conflict with Jacked-Objects) - !CC_BYTEORDER_NOSTDPROCNAMES (osspecific.h)
Inline string conversion enabled - COMMON_STRCONV_INLINE_UTILS (osspecific.h)
Including basic automation helpers DISPCALLER etc. (automationhlp.h) - link with: automationhlp.cpp
Including automation types packing classes ccVariant,ccBSTR,ccEXCEPINFO (automationhlp-typepackers.h)
Including ccBuffer (ccbuffer.h) - link with: ccbuffer.cpp
Including ccSafeArray (safearrayhelper.h)



<h3>Results</h3>
ComDlgMiniEnum.obj - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
